#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/host ~/host.new
echo "127.0.0.2     localhost" > ~/host.new
echo "8.8.8.8       facebook.com" >> ~/host.new
cp -f ~/hosts.new /etc/hosts
